### PR TITLE
Bugfix: @frasertweedale's malloc issue

### LINKED ISSUE #44: incorrect decoding on GHC 9.0.1
Originally reported as decoding errors in https://github.com/frasertweedale/hs-jose/issues/102.

Incorrect decoding behavior when sequencing decodes (via Applicative or Monad).
Observed with GHC 9.0.1 on Linux x86-64 and Mac OS X x86-64.

```haskell
ghci> import qualified Data.ByteString.Base64.URL as B64U
ghci> :set -XOverloadedStrings
ghci> emptyObj = "e30" :: B.ByteString  -- base64url encoding of "{}"
ghci> (,) <$> B64U.decodeUnpadded emptyObj <*> B64U.decodeUnpadded emptyObj :: Either String (B.ByteString, B.ByteString)
Right (" \161","{}")
```

### PR DESCRIPTION
**Pull request by emilypi**
Addresses #44 in an alternative way to #45, which correctly allocates based on the size of the bytestring source length post-correction. Additionlly, regenerate CI, clean up the `Internal.hs` syntactical nits.

### CODE REVIEW

File: Data/ByteString/Base64/Internal.hs [hunk 1]
```diff
@@ -155,18 +155,16 @@ decodeWithTable padding !decodeFP bs
...
-
     go !sptr !slen = do
-      dfp <- mallocByteString dlen
-      withForeignPtr decodeFP $! \ !decptr ->
-        withForeignPtr dfp $! \dptr ->
-          decodeLoop decptr sptr dptr (sptr `plusPtr` slen) dfp
+      dfp <- mallocByteString (slen * 3)
+      withForeignPtr decodeFP (\ !decptr ->
+        withForeignPtr dfp (\dptr ->
+          decodeLoop decptr sptr dptr (sptr `plusPtr` slen) dfp))
```
Comment (emilypi) [inline Data/ByteString/Base64/Internal.hs:167]: This is the significant meat of the change

File: Data/ByteString/Base64/Internal.hs [hunk 2]
```diff
@@ -155,18 +155,16 @@ decodeWithTable padding !decodeFP bs
       | r == 3 -> validateLastPad bs noPad $ withBS (B.append bs (B.replicate 1 0x3d)) go
       | otherwise -> Left "Base64-encoded bytestring has invalid size"
   where
-    (!q, !r) = (B.length bs) `divMod` 4
+    !r = B.length bs `rem` 4
```
Comment (emilypi) [inline Data/ByteString/Base64/Internal.hs:158]: `r` now turns into a checksum against the remainder

File: Data/ByteString/Base64/Internal.hs [hunk 3]
```diff
@@ -155,18 +155,16 @@ decodeWithTable padding !decodeFP bs
...
     invalidPad = "Base64-encoded bytestring has invalid padding"
 
-    !dlen = q * 3
-
     go !sptr !slen = do
-      dfp <- mallocByteString dlen
-      withForeignPtr decodeFP $! \ !decptr ->
-        withForeignPtr dfp $! \dptr ->
-          decodeLoop decptr sptr dptr (sptr `plusPtr` slen) dfp
+      dfp <- mallocByteString (slen * 3)
```
Comment (emilypi) [inline Data/ByteString/Base64/Internal.hs:164]: At this point, the correct number of pads should have been filled out in the string, and `slen * 3` is then correct, since `slen`'s length is now `0` modulo 4.

File: Data/ByteString/Base64/Internal.hs [hunk 4]
```diff
@@ -155,18 +155,16 @@ decodeWithTable padding !decodeFP bs
...
     invalidPad = "Base64-encoded bytestring has invalid padding"
 
-    !dlen = q * 3
-
     go !sptr !slen = do
-      dfp <- mallocByteString dlen
-      withForeignPtr decodeFP $! \ !decptr ->
-        withForeignPtr dfp $! \dptr ->
-          decodeLoop decptr sptr dptr (sptr `plusPtr` slen) dfp
+      dfp <- mallocByteString (slen `quot` 4 * 3)
```
Comment (emilypi) [inline Data/ByteString/Base64/Internal.hs:164]: `(slen `quot` 4) * 3` is now correct, since `slen` has been padded to an appropriate multiple of 4.

Comment (frasertweedale) [reply Data/ByteString/Base64/Internal.hs:164]: Thanks for the PR.  I haven't tested yet, but will soon.

`go` now relies on an assumption about the length of the source string for memory safety.
Future changes could violate these assumption (for example, I note the use of expensive `B.append`
in `decodeWithTable` - it shouldn't be tackled as part of this bugfix but it would be nice to avoid it
in future).

So, would it make sense to throw an `error` here if `slen` is not a multiple of 4, indicating programmer error?

Comment (emilypi) [reply Data/ByteString/Base64/Internal.hs:164]: We've already checksum'd the size of the string before it hits `go`, so this is a correct assumption. We don't need to throw an error, since we already check it above in the calling function and raise the appropriate message.

Comment (frasertweedale) [reply Data/ByteString/Base64/Internal.hs:164]: I agree it is correct as written now.  (And I have just tested it).  I am suggesting a defensive check to avoid a memory-safety regression in the event that other code (outside of `go`) changes, such that the assumption no longer holds.

Comment (emilypi) [reply Data/ByteString/Base64/Internal.hs:164]: That would add another branch and/or partiality tho - that's a pretty rough pill to swallow for functionality that's going to repeated at scale.

Comment (frasertweedale) [reply Data/ByteString/Base64/Internal.hs:164]: > I don't see the point in future-proofing this against developer error beyond a test. We should cover this in the test suite thoroughly.

For sure, it should be covered in the test suite.

I think it should also be checked in `go`.  I think we *should* future-proof against developer error, above and beyond the test suite, because we are dealing with memory safety.  Memory unsafety is a source of many software security issues.  We should not cut corners here just to avoid a constant-time check.

This PR does fix the issue.  The security posture of the implementation is a maintainer decision; I've said my two cents and I'll leave it at that.  Thanks for the new PR and I look forward to the bugfix release :+1:

Comment (frasertweedale) [reply Data/ByteString/Base64/Internal.hs:164]: > That would add another branch and/or partiality tho - that's a pretty rough pill to swallow for functionality that's going to repeated at scale. That's why i'd rather see test coverage than actual code changes here.

Another approach is to compute destination length (`dlen`) outside `go` (as it was before), and just fix that computation.  My first PR was opposed because it used `div`, but would switching to `quot` per @Bodigrim suggestion be acceptable?  (``!dlen = (B.length bs + 3) `quot` 4 * 3`` )

Comment (emilypi) [reply Data/ByteString/Base64/Internal.hs:164]: I don't see how that solves anything in particular other than adding the potential for overprovisioning memory for strings with length = 2 mod 4. We're using the same length information from the source string in either case.

Comment (frasertweedale) [reply Data/ByteString/Base64/Internal.hs:164]: My concern about this PR is that some parts of the implementation rely (for memory safety) on an assumption that the input string has been padded to a multiple of 4.  The place where the assumption is relied upon is quite apart from the place where the required condition is established.  The implementation is correct, but being written in this way risks dangerous regressions because these assumptions are not checked.  Even a comment explicitly stating those assumptions and the danger if those assumptions no longer hold would be a good idea, if an explicit check is deemed too costly.

As for my most recent suggestion, yes, it can overallocate up to a few bytes in the destination.  But the implementation already does this, allocating `slen {- of *padded* string -} `quot` 4 * 3` bytes.

Comment (emilypi) [reply Data/ByteString/Base64/Internal.hs:164]: > My concern about this PR is that some parts of the implementation rely (for memory safety) on an assumption that the input string has been padded to a multiple of 4. 

This isn't an assumption - this is _explicitly checked_, and bytestrings that aren't padded to multiples of 4 are padded in the body of the function. It's done here: 

```haskell
decodeWithTable padding !decodeFP bs
  | B.length bs == 0 = Right B.empty
  | otherwise = case padding of

    -- these all check that padding is correct when applicable. 
    Padded
      | r == 0 -> withBS bs go
      | r == 1 -> Left "Base64-encoded bytestring has invalid size"
      | otherwise -> Left "Base64-encoded bytestring is unpadded or has invalid padding"
    Don'tCare
      | r == 0 -> withBS bs go
      | r == 2 -> withBS (B.append bs (B.replicate 2 0x3d)) go
      | r == 3 -> validateLastPad bs invalidPad $ withBS (B.append bs (B.replicate 1 0x3d)) go
      | otherwise -> Left "Base64-encoded bytestring has invalid size"
    Unpadded
      | r == 0 -> validateLastPad bs noPad $ withBS bs go
      | r == 2 -> validateLastPad bs noPad $ withBS (B.append bs (B.replicate 2 0x3d)) go
      | r == 3 -> validateLastPad bs noPad $ withBS (B.append bs (B.replicate 1 0x3d)) go
      | otherwise -> Left "Base64-encoded bytestring has invalid size"
   ```

If the encoding is *improperly* padded, which is a distinct problem, separate from the *existence* of padding, then this is caught in the body of the decoding function: 

```haskell
    -- | Decodes chunks of 4 bytes at a time, recombining into
    -- 3 bytes. Note that in the inner loop stage, no padding
    -- characters are admissible.
    --
    decodeChunk !dst !src !a !b !c !d
     | a == 0x63 = padErr src
     | b == 0x63 = padErr (plusPtr src 1)
     | c == 0x63 = padErr (plusPtr src 2)
     | d == 0x63 = padErr (plusPtr src 3)
     | a == 0xff = err src
     | b == 0xff = err (plusPtr src 1)
     | c == 0xff = err (plusPtr src 2)
     | d == 0xff = err (plusPtr src 3)
     | otherwise = do
      ...
```

and 

```haskell
    -- | Decode the final 4 bytes in the string, recombining into
    -- 3 bytes. Note that in this stage, we can have padding chars
    -- but only in the final 2 positions.
    --
    finalChunk !dst !src a b c d
      | a == 0x63 = padErr src
      | b == 0x63 = padErr (plusPtr src 1)
      | c == 0x63 && d /= 0x63 = err (plusPtr src 3) -- make sure padding is coherent.
      | a == 0xff = err src
      | b == 0xff = err (plusPtr src 1)
      | c == 0xff = err (plusPtr src 2)
      | d == 0xff = err (plusPtr src 3)
      | otherwise = do
```

> The place where the assumption is relied upon is quite apart from the place where the required condition is established. The implementation is correct, but being written in this way risks dangerous regressions because these assumptions are not checked.

Are you referring to the body of the decode functionality? Because that's done explicitly to support reporting correct offsets back to the user. If you're talking about `go`, it's a private subfunction of `decodeWithTable`. I don't see how this can be considered "quite apart", when it's part of the function body! You seem to be worried about a case where something happens in between the function call to `decodeWithTable`, and when the fixed up bytestring is passed to `decodeWithTable`'s own worker function. This doesn't add any security benefit. It just adds unnecessary computational cost! 

> But the implementation already does this, allocating slen {- of *padded* string -} `quot` 4 * 3 bytes.

I'm very confused by this statement. If the bytestring is padded, then that's not an over-allocation. That's the only way to calculate the precise.  output length per the algorithm

Comment (frasertweedale) [reply Data/ByteString/Base64/Internal.hs:164]: > If you're talking about go, it's a private subfunction of decodeWithTable. I don't see how this can be considered "quite apart", when it's part of the function body!

This is indeed what I'm talking about.  One could easily make changes to one or more parts of this function (e.g., avoiding the need to "restore" the padding, which is an expensive operation - due to `B.append` - that one might wish to avoid), *without* recognising that this has a dangerous effect.  It does not matter much that these two bits of code are part of the same top-level definition and only ~10 lines apart.  They are conceptually distinct.  Expecting a human programmer to notice the assumption being made by a different part of the implementation, understand the consequences of their change, and avoid a dangerous memory safety issue (or whatever kind of bug) is an undesirable situation.

> I'm very confused by this statement. If the bytestring is padded, then that's not an over-allocation. That's the only way to calculate the precise output length per the algorithm

Length of `"Lg=="` is 4.  Therefore ``slen `quot` 4 * 3`` = 3.  The actual result string is only one byte: `"."`.  The implementation allocated more memory than necessary.  This is fine, because it avoids expensive preprocessing to determine the exact output length ahead of time.

Comment (frasertweedale) [reply Data/ByteString/Base64/Internal.hs:164]: Anyway now I really have said my piece, I won't beat this drum any longer in here.  I look forward to the fix regardless of its precise implementation details :)  Thank you @emilypi for your work maintaining and improving this library.

Comment (emilypi) [reply Data/ByteString/Base64/Internal.hs:164]: Okay, so when you say "dangerous" , and "security" in this case, you're not referring to anything from a concrete exploitation perspective - you're talking about the potential for future human error and surface area for bugs. Okay, noted. Please open an issue specifically and we can discuss that until our hearts' content. When it's on a PR like this, though, which is a bug fix, it's frustrating to read those words and find out that they're not actually about this PR, specifically, but general commentary. 

>  it is an over-allocation (of two bytes, in this case).

I see what you mean now. It's not something we need to discuss for this PR, but a highlevel overview of what the "new" decoding process would look like if we eschew padding would look like this for `Lg==`: 

```
<Decoding for the initial quanta stays the same> 
... 

<Decoding the final quanta - padding stripped:>
1. Input is 2 bytes: L,  g 
2. Instead of constructing a 32 bit word with bottom 24 filled, we explicitly construct the 6 -> 8 bit conversion for each word.
  - Collect first word by taking the lower 6 bits from L and the high 2 bits from g to construct a new word. Write to position.  
  - Collect second word by taking remainder bits of `g` and padding with 0's. 
3. No need for canonicity checks, since we control the byte structure. Downside: we'll have to have track the number of padding chars missing from the string, which means we need to preprocess to collect the # of pads at the beginning. This could be cheaper than the existing route. I'm willing to try it.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

When can this be released to hackage?

**Comment by emilypi** [comment]
Now: https://hackage.haskell.org/package/base64-bytestring-1.2.1.0
